### ISSUE TITLE
Consider adding `passengerAges: Array` to FlightBooking.itinerary

### ISSUE THREAD

**Issue by randunel** [universalbasket/protocol#11]
We'd need this in order to crawl, or to start a checkout without knowing all the passenger details.

This would be a requirement for all b2c clients, i.e. KY, SL and SS.

**Comment by inca** [comment]
I'd rather go with separating `itinerary` from these details. Consider adding a top level `flightSearchRequest` instead with all necessary details to complete the "home page".

Btw we had a somewhat related discussing with @1602, so please share your input here.

**Comment by randunel** [comment]
If we add them, we must add them now or much later.

**Comment by randunel** [comment]
The :ship: has sailed, for now. We will probably add this as an optional field when it's required.
