### ISSUE TITLE
Add flight search params with passenger ages to FlightBooking, retiring itinerary

### ISSUE THREAD

**Issue by randunel** [universalbasket/protocol#22]
(removed `*inbound*` and `countryCode` keys for simplicity)

## Current setup

```
           +> cabinClass
           |
itinerary ++            +> origin +--> dateTime
           |            |         |
           +> outbound ++         +--> airportCode
                        |
                        |
                        +> destination +--> dateTime
                                       |
                                       +--> airportCode


passengers +-> 0 +-> dateOfBirth
           |
           +-> 1 +-> dateOfBirth
           |
           +->
           |
           +->

```

## Proposal

```

search +-> cabinClass (/itinerary/cabinClass)
       |
       +-> outbound +-> origin +-> date (/itinerary/outbound/origin/dateTime without time)
       |            |          |
       |            |          +-> airportCode (/itinerary/outbound/origin/airportCode)
       |            |
       |            +-> destination +-> date
       |                            |
       |                            +-> airportCode
       |
       +-> passengerAges (/passengers/n/dateOfBirth & /itinerary/outbound/origin/dateTime)


selectedOutboundFlight +-> origin +-> dateTime (/itinerary/outbound/origin/dateTime)
                       |          |
                       |          +-> airportCode (/itinerary/outbound/origin/airportCode)
                       |
                       |
                       +-> destination +-> dateTime
                                       |
                                       +-> airportCode


passengers +-> 0 +-> dateOfBirth
           |
           +-> 1 +-> dateOfBirth
           |
           +->
           |
           +->

```

## Rationale

All flight search forms require a minimum set of parameters in order to reach the results, as shown in the images below:

![British Airways](https://user-images.githubusercontent.com/1965181/36197285-0aade586-117c-11e8-9fce-925477514477.png)
![Lufthansa](https://user-images.githubusercontent.com/1965181/36197294-0ecd313a-117c-11e8-9e08-99cc85eb2b27.png)

By oversupplying `/itinerary` with `time` parameters, we were forcing clients to attain knowledge of an exact flight before creating a job. Besides, all search forms require the count and age group of passengers, which we were calculating from each passenger's date of birth, thus forcing our clients to supply full passenger information without them having seen any results from us.

This proposal splits the minimum required information into the `search` top level key: `cabinClass`, `origin with date`, `destination with date` and `passengerAges`, leaving the flight selection information as a separate `selctedOutboundFlight` top level key, which may be supplied later.

## First iteration
In order to be backwards compatible, we must:
- only require the information already being supplied, so that we may build a translation layer which converts old->new inputs and viceversa;
- similar to `itinerary` and `passengers`, require `search`, `selectedOutboundFlight` and `selectedInboundFlight` as initial data. Clients will be able to supply the last 2 later (non-initial), when we remove the translation layer.

In order to not introduce breaking changes later, we must now require `selectedOutboundFlight` and `selectedInboundFlight` without them being an actual selection. We will introduce `outboundFlights` and `inboundFlights` outputs once the translation layer has been removed.

## Later iterations

As the name suggests, `selectedOutboundFlight` will be a choice 1 of many. Similar to `selectedOutboundFare` (notice flight vs fare word ending), there will be a corresponding output `outboundFlights`.

We have multiple possibilities for this output, but clients may expect and we must require the `origin/dateTime` as a minimum, as this is the only information that is available on all the flight results pages. All other information (flight codes, airport codes, duration, destination date/time) would be optional, as this is inconsistent throughout the industry.

#### Option 1. Multiple outputs and corresponding inputs for flights and fares
This is one of the two backwards compatible options for flights and fares outputs. It is also the easiest for us to implement, as we have most of the necessary tooling covered by *UDF*.
```diff
+1. output `/availableOutboundFlights`
[{
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 08:37" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 10:09" }
}, {
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 12:25" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 14:00" }
}, {
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 18:35" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 22:07" }
}]

-2. input `/selectedOutboundFlight`
{
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 18:35" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 22:07" }
}

+3. output `/availableOutboundFares`
[{
    "cabinClass": "economy",
    "fareName": "Economy Standard",
    "price": { "value": 3000, "currencyCode": "gbp" }
}, {
    "cabinClass": "premium economy",
    "fareName": "Premium Economy",
    "price": { "value": 4500, "currencyCode": "gbp" }
}, {
    "cabinClass": "business",
    "fareName": "Business Standard",
    "price": { "value": 7800, "currencyCode": "gbp" }
}]

-4. input `/selectedOutboundFare`
{
    "cabinClass": "economy",
    "fareName": "Economy Standard",
    "price": { "value": 3000, "currencyCode": "gbp" }
}
```
#### Option 2. Multiple outputs, flights with fares included and separate fares afterwards
This would be one of the two backwards compatible options.

The main advantage of this one over **Option 1** is that the client is able to see the available prices and fares before selecting a flight, which may matter when their user is looking for a specific cabin class or to compare prices earlier.

The main disadvantage is that there is redundant information being output the second time around. We should consider not having the second output, `+3. output /availableOutboundFares`, but this leads to backwards incompatibility and possible client confusion.

There are possible problems with this approach, same as **Option 3**. We don't always have the fares shown upfront, and we would be required to click on each row to collect the fares. The most prominent website with this behaviour is British Airways, the *modern* checkout flow. **See self explanatory images below**.
```diff
+1. output /availableOutboundFlights
[{
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 08:37" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 10:09" },
    "availableFares": [
        {
            "cabinClass": "economy",
            "fareName": "Economy Standard",
            "price": { "value": 3000, "currencyCode": "gbp" }
        },
        {
            "cabinClass": "premium economy",
            "fareName": "Premium Economy",
            "price": { "value": 4500, "currencyCode": "gbp" }
        }
    ]
}, {
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 12:25" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 14:00" },
    "availableFares": [
        {
            "cabinClass": "economy",
            "fareName": "Economy Standard",
            "price": { "value": 3500, "currencyCode": "gbp" }
        },
        {
            "cabinClass": "premium economy",
            "fareName": "Premium Economy",
            "price": { "value": 5100, "currencyCode": "gbp" }
        }
    ]
}, {
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 18:35" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 22:07" },
    "availableFares": [
        {
            "cabinClass": "economy",
            "fareName": "Economy Standard",
            "price": { "value": 2900, "currencyCode": "gbp" }
        },
        {
            "cabinClass": "premium economy",
            "fareName": "Premium Economy",
            "price": { "value": 4350, "currencyCode": "gbp" }
        },
        {
            "cabinClass": "business",
            "fareName": "Business Standard",
            "price": { "value": 7800, "currencyCode": "gbp" }
        }
    ]
}]

-2. input /selectedOutboundFlight
{
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 18:35" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 22:07" }
}

+3. output /availableOutboundFares
[{
    "cabinClass": "economy",
    "fareName": "Economy Standard",
    "price": { "value": 2900, "currencyCode": "gbp" }
}, {
    "cabinClass": "premium economy",
    "fareName": "Premium Economy",
    "price": { "value": 4350, "currencyCode": "gbp" }
}, {
    "cabinClass": "business",
    "fareName": "Business Standard",
    "price": { "value": 7800, "currencyCode": "gbp" }
}]

-4. input /selectedOutboundFare
{
    "cabinClass": "economy",
    "fareName": "Economy Standard",
    "price": { "value": 2900, "currencyCode": "gbp" }
}
```
#### Option 3. Single output of a flattened flights+fares array and single flight+fare selection
There are possible problems with this approach, same as **Option 2**. We don't always have the fares shown upfront, and we would be required to click on each row to collect the fares. The most prominent website with this behaviour is British Airways, the *modern* checkout flow. **See self explanatory images below**.
```diff
+1. output /availableOutboundFlights
[{
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 08:37" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 10:09" },
    "cabinClass": "economy",
    "fareName": "Economy Standard",
    "price": { "value": 3000, "currencyCode": "gbp" }
}, {
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 08:37" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 10:09" },
    "cabinClass": "premium economy",
    "fareName": "Premium Economy",
    "price": { "value": 4500, "currencyCode": "gbp" }
}, {
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 18:35" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 22:07" },
    "cabinClass": "economy",
    "fareName": "Economy Standard",
    "price": { "value": 2900, "currencyCode": "gbp" }
}, {
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 18:35" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 22:07" },
    "cabinClass": "premium economy",
    "fareName": "Premium Economy",
    "price": { "value": 4350, "currencyCode": "gbp" }
}, {
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 18:35" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 22:07" },
    "cabinClass": "business",
    "fareName": "Business Standard",
    "price": { "value": 7800, "currencyCode": "gbp" }
}]

-2. input /selectedOutboundFlight
{
    "origin": { "airportCode": "LHR", "dateTime": "2018-01-01 18:35" },
    "destination": { "airportCode": "MUC", "dateTime": "2018-01-01 22:07" },
    "cabinClass": "premium economy",
    "fareName": "Premium Economy",
    "price": { "value": 4350, "currencyCode": "gbp" }
}
```

#### Problems with Options 2 and 3, in images:

![British Airways](https://user-images.githubusercontent.com/1965181/36206893-b09a3ede-119c-11e8-8b3a-4ef8aded4883.png)
![Lufthansa](https://user-images.githubusercontent.com/1965181/36207018-25bb0b4e-119d-11e8-87ab-506955a9b1f1.png)

**Comment by marcusgreenwood** [comment]
ideally should be a mandatory field but only if translation layer can translate data before validation happens

**Comment by nicck** [comment]
translation layer needs valid data to translate, so seems like validation should (and it does in https://github.com/universalbasket/service-api/pull/418) go first.

**Comment by mprussell** [comment]
Opt 3. seems to have consensus here, but there's a question:

Can we still support a single flight based on time? i.e. as in the current flow where the customer is deliberately picking a single option before we return the options.

**Comment by randunel** [comment]
We are quite far away from either Option 2 or 3, whereas Option 1 would be available to us to experiment with later this month.
