### ISSUE TITLE
Research: Receive PAN and CVV concurrently

### ISSUE THREAD

**Issue by mprussell** [universalbasket/protocol#26]
KAYAK would like to send both PAN and CVV to the same endpoint concurrently. 

There may be a possibility for them to change this their end, and they're estimating the impact of doing this. We promised to look into it our end.

Can we explore (quick) solutions to achieve this our end so we can communicate with KAYAK the possibilities. Suggestions in Comments please.

**Comment by randunel** [comment]
In order to remain PCI-DSS compliant, under no circumstances are we to store the CVV, encrypted or not, past the end of the transaction it was required for.

**Comment by marcusgreenwood** [comment]
What if we don't store it, we just encrypt it and send it back. Could append onto the `panToken`

**Comment by randunel** [comment]
- PAN is required once, before any jobs run. It will be reused for `n` jobs;
- CVV is required for every job. It may only be used for `1` job.

The misunderstanding is this: they don't need to vault the card for every job, but only once, before all jobs.

**Comment by marcusgreenwood** [comment]
current flow

export VAULT_API="https://vault.automationcloud.net"

```
curl -X POST "$VAULT_API/pan" \
  -d@- <<EOF
  {
    "otp": "5a319910-4f4e-4f62-a8a5-a9d11d67d199",
    "pan": "4111111111111111"
  }
EOF
```

Proposed flow

```
export VAULT_API="https://vault.automationcloud.net"

curl -X POST "$VAULT_API/pan" \
  -d@- <<EOF
  {
    "otp": "5a319910-4f4e-4f62-a8a5-a9d11d67d199",
    "pan": "4111111111111111",
    "cvv": "123"
  }
EOF
```

Response

```
{
  "object": "decryption",
  "id": "401d406f-b39a-49b6-9c3f-4c0c820f4370",
  "key": "a23a64f4b14ae79ea7a26c440d9e4dac-132f73475acd8dd7dd8f7ec85d453c0a-998b41c0c207917351889f314026f670-123encrypted"
}
```

**Comment by marcusgreenwood** [comment]
Then in `panExchange`, it can just grab the `cvv` part from the end and decrypt it with a shared key (e.g. `liverp00l` 😂). Ergo we don't store it. We just encrypt/decrypt it.

**Comment by randunel** [comment]
This proposal means that our client stores it (in an encrypted form, as part of the decryption key). If they want to remain PCI-DSS compliant, they will refuse to do so.

**Comment by marcusgreenwood** [comment]
lol. well technically it's not stored. it's just passed through in transit.

**Comment by marcusgreenwood** [comment]
oh. my mistake. I meant to put this on `/pan/temporary` rather than `/pan`

**Comment by randunel** [comment]
^ This should work, it's one of the possibilities.

As it may constitute incidental storage, we must be careful and warn them to delete the token. I think we can or should find a way that doesn't risk client side incidental storage, since our vault is in communication with service-api, anyway.

**Comment by emmasalih** [comment]
We have agreed to let Kayak develop a solution which works for our existing flow so no development requirement from our end as this is the most reliable option available.
