### ISSUE TITLE
Add ability specify selection rules

### ISSUE THREAD

**Issue by 1602** [universalbasket/protocol#32]
Use case: for some inputs we intent to select something from corresponding output (`SelectOne` and `Consent` rules).

Currently this knowledge hard-coded on a client-side (e.g. `selectedOutboundFare` can be calculated using `SelectOne` rule and `availableOutboundFares` as a data source).

This proposal is about adding a configuration to input key which will specify allowed selection rule (nullable enum of [`SelectOne`, `Consent`] currently) and data source (name of corresponding output key).

**Comment by emmasalih** [comment]
Assumed this is done. cc @1602
