### ISSUE TITLE
Add metropolitan groups to airport codes

### ISSUE THREAD

**Issue by randunel** [universalbasket/protocol#36]
Groups of airports also belong to metropolitan groups with their own code identifiers. For example:

|Group code|Airport codes|
|-----|-----|
|LON|LHR,LGW,STN,LTN,LCY,SEN,FAB|
|NYC|JFK,EWR,LGA|
|BUC|OTP,BBU|

Some websites, such as SwissAir (live), only allow searches by metro group codes. Since this type of information is readily available online and pretty much static, we should either ask for it or determine it outselves.

**Comment by emmasalih** [comment]
Do you mean to for it from user in the protocol or we translate some of it by ourselves when user sends airport code?  

How do you get around this currently when scripting? Does it just fail?

**Comment by randunel** [comment]
> Do you mean to for it from user in the protocol or we translate some of it by ourselves when user sends airport code?
I mean either get it from client, or translate it ourselves, yes.

> How do you get around this currently when scripting? Does it just fail?
Swiss, Iberia, Emirates (possibly others) just fail. They only work with deeplinks.

**Comment by emmasalih** [comment]
I'm assuming this doesn't affect existing scripts. Does this affect any upcoming ones? Trying to understand priority from your point of view. Thanks

**Comment by emmasalih** [comment]
moved to j
