### ISSUE TITLE
Describe availability of rule for input key

### ISSUE THREAD

**Issue by 1602** [universalbasket/protocol#39]
Some input keys allow certain methods of producing input data, currently hard-coded in UI and backend code. Such as:
- allow `Const` for all keys except `panToken`
- `SelectOne` and `SelectAll` works for `selectedOutboundFare` and `selectedInboundFare`
- `SelectSeats` works for `selectedSeats` (only available within FlightBooking domain)
- `Consent` works for `finalPriceConsent`

In order to be able to maintain multiple domains across QA tooling infrastructure we should move this knowledge into protocol, as input configuration.

**Comment by 1602** [comment]
Proposal for protocol meta update: add `allowedInputMethods: array of string` to input definition.

**Comment by emmasalih** [comment]
When do we need this? If we update protocol will client see this?

**Comment by 1602** [comment]
> When do we need this?
We need this when we want to start creating scenarios for any domain, not just flight-booking and motor insurance.
>  If we update protocol will client see this?
Yes, and no. Status of the protocol is public, but not limited to only public features.

**Comment by muzafarova** [comment]
This also unlocks simplified scenario UI when user just selects a key and then (based on protocol meta information) chooses from available "decision" options (select one, select all, go with constant piece of JSON) – currently things like this are hardcoded in backoffice

**Comment by emmasalih** [comment]
I believe this is done (even if its in another way)
