### ISSUE TITLE
Input node extensibility

### ISSUE THREAD

**Issue by 1602** [universalbasket/protocol#5]
Current input node looks like:

```json
{
    "$ref": "#DomainName.TypeName",
    "$id": "#DomainName.TypeName"
}
```

We have extensibility issue here, even having "$id" nearby the "$ref" causes a bit of confusions (because some implementation implement json schema spec more carefully than ajv 😿), and we might need more input-node-level features (currently I'm working on input variations spec), so I suggest moving $ref to deeper scope, unlocking possibilities for extending input node.

Proposal:

```json
{
    "$id": "#DomainName.TypeName",
    "typeDef": { "$ref": "#Generic.TypeName" },
    "variation": "...",
    "other-feature": "..."
}
```

Alternatively, we might consider other place to put things like variations. Input node might not be the right place for semantic validation (if we decide to have it), since some of the validations actually cross-nodes, e.g. passengers array should have same length as passengerAges array.

**Comment by inca** [comment]
There's been a lot of related discussions outside this topic, so sharing conclusions:

- we agreed on making `inputs` and `outputs` custom objects (not JSON schema types), which means we're free to extend them with our metadata without the fear of name collisions
- we're getting rid of `$id` in favor of JSON pointers; public API will still expose more specialised methods for accessing definitions and validating objects against them, so this change will be transparent
- the only thing that will change is `$ref` resolution — but I'm keen on keeping it very strict via `pattern` in meta schema
