### ISSUE TITLE
Common service attributes

### ISSUE THREAD

**Issue by 1602** [universalbasket/protocol#66]
Services across all domains may share common attributes. It is currently problematic to work with common attributes across all domains, since it involves manual update of all domain adding same exact schemata everywhere, which is bad design because there's no guarantee of sameness of common attributes schemata, and as we add more domains and more attributes we may break dependencies depending on schemata consistency across all domains.

This is tech-debt payoff kind of issue, which intends to revisit existing solution according to new use cases we've recently discovered.

This debt introduced in order to unblock progress in Guided Docs project, in order to allow running guided jobs in domains other than FlightBooking.

**Comment by emmasalih** [comment]
moved to jira
