### ISSUE TITLE
Consider adding additionalProperties: false to most definitions

### ISSUE THREAD

**Issue by inca** [universalbasket/protocol#7]
This very important feature will keep objects strict and tidy, resolving all kinds of ambiguities.
Additionally, add indication in docs that object is "loose".

@randunel please confirm we can do that, since it is possibly a breaking change to existing clients.

**Comment by randunel** [comment]
As long as it's in sandbox, it's ok. Don't do it in production, as TP always oversupply passenger IDs.

**Comment by emmasalih** [comment]
What's the point of having this in sandbox only?

**Comment by randunel** [comment]
We shouldn't restrict oversupply in production (schema/RFI) because one of the clients already oversupplies. We should only restrict it in MIMO

**Comment by inca** [comment]
I think this note added a bit of confusion since there's no protocol in production. Anyhow, it's already done, we expect clients to remove their additional properties when they catch up with mimo release.
