### ISSUE TITLE
Require flight code as part of booking input

### ISSUE THREAD

**Issue by randunel** [universalbasket/protocol#79]
This is a very important requirement for airlines with codeshares and OTAs.

This is a not-very-important requirement for flights with 2 or more stopovers.

![austrian-price-flight-diff 1](https://user-images.githubusercontent.com/1965181/32845027-71bd5c76-ca2c-11e7-819c-2469b3511cd1.jpg)

![lufthansa](https://user-images.githubusercontent.com/1965181/32881118-c33c94a4-cab8-11e7-929a-c39af0c67661.png)

**Comment by emmasalih** [comment]
moved to jira
