### ISSUE TITLE
Protocol website requires some scrolling love

### ISSUE THREAD

**Issue by uaffs** [universalbasket/protocol#89]
![image](https://user-images.githubusercontent.com/11519124/53174617-e8774880-35f2-11e9-83b7-2c09ba1e6956.png)

Have zone 1 as scrollable independent of zone 2. Right now to scroll lower in zone 1 I have to scroll all the way down in zone 2.
Issue can be reproduced by visiting https://protocol.automationcloud.net/LoanApplication#url (as an example) and trying to go to HolidayBooking domain (which is lower in the zone 1 list)

**Comment by inca** [comment]
[Fixed](https://github.com/universalbasket/protocol/commit/ce8fd87b03373ad554a40245d3aae4aa8aa0828e)
